In [1]:
import numpy as np

A = np.array([[1, 2],   # 2行2列
              [3, 4]])
B = np.array([[5, 6],   # 2行2列
              [7, 8]])

# 请你在脑子里算一下：A 乘 B 的结果第一行第一列是多少？(1*5 + 2*7 = 19)
# 敲代码验证：
print(A @ B)  
# 检查结果是否等于 [[19, 22], [43, 50]]

[[19 22]
 [43 50]]


In [2]:
# 创建一个 3行4列 的矩阵
mat = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12]])

# 创建一个 只有1行4列 的小数组
vec = np.array([1, 10, 100, 1000])

# 两者相加，观察结果（你会看到 vec 自动复制了3行，每一行都加了上去）
print(mat + vec)

[[   2   12  103 1004]
 [   6   16  107 1008]
 [  10   20  111 1012]]


In [3]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

In [4]:
print("默认全部求和（整个矩阵）：", np.sum(data))      # 45
print("axis=0（纵向，求每列和）：", np.sum(data, axis=0)) # [12, 15, 18]（1+4+7，2+5+8...）
print("axis=1（横向，求每行和）：", np.sum(data, axis=1)) # [6, 15, 24]（1+2+3，4+5+6...）

默认全部求和（整个矩阵）： 45
axis=0（纵向，求每列和）： [12 15 18]
axis=1（横向，求每行和）： [ 6 15 24]
