In [1]:
import numpy as np
print("NumPy 导入成功！版本:", np.__version__)

ModuleNotFoundError: No module named 'numpy'

In [2]:
import sys
print(sys.executable)

C:\python\python.exe


In [3]:
import numpy as np
print("NumPy 导入成功！版本:", np.__version__)

NumPy 导入成功！版本: 2.5.1


In [4]:
arr1 = np.array([10, 20, 30, 40, 50])
print("一维数组:", arr1)
print("形状:", arr1.shape)

一维数组: [10 20 30 40 50]
形状: (5,)


In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("二维数组:\n", arr2)
print("第一行:", arr2[0, :])
print("第三列:", arr2[:, 2])

二维数组:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
第一行: [1 2 3]
第三列: [3 6 9]


In [6]:
arr3 = np.arange(12).reshape(3, 4)
print("reshape 3x4:\n", arr3)

reshape 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
print("2x3 全零:\n", np.zeros((2, 3)))
print("3x2 全一:\n", np.ones((3, 2)))
print("4x4 随机:\n", np.random.rand(4, 4))

2x3 全零:
 [[0. 0. 0.]
 [0. 0. 0.]]
3x2 全一:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
4x4 随机:
 [[0.0639827  0.24972236 0.08036443 0.79313513]
 [0.53180139 0.15485172 0.36641719 0.98490667]
 [0.32461843 0.80025042 0.63970045 0.17604434]
 [0.35834636 0.34002328 0.37821594 0.24398655]]
