# PyTorch 张量基础（CPU 环境）
我使用的是 CPU 版 PyTorch，所有操作正常运行。

In [2]:
import torch
import numpy as np

# 1. 从列表创建
t1 = torch.tensor([1, 2, 3, 4])
print("t1:", t1)
print("形状:", t1.shape)        # torch.Size([4])
print("数据类型:", t1.dtype)    # torch.int64

# 2. 特殊初始化（全零、全一、随机）
zeros = torch.zeros(2, 3)       # 2行3列全0
ones = torch.ones(2, 3)         # 全1
rand = torch.rand(2, 3)         # 0~1随机数
print("全零:\n", zeros)
print("全一:\n", ones)
print("随机:\n", rand)

# 3. 指定小数类型（深度学习常用 float32）
t2 = torch.tensor([1.5, 2.5], dtype=torch.float32)
print("指定 float32:", t2.dtype)

t1: tensor([1, 2, 3, 4])
形状: torch.Size([4])
数据类型: torch.int64
全零:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
全一:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
随机:
 tensor([[0.8406, 0.4763, 0.8682],
        [0.6548, 0.7444, 0.3575]])
指定 float32: torch.float32


In [3]:
# 把整数张量改成浮点数，看看会发生什么
t3 = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print(t3.dtype)  # 输出 torch.float32

torch.float32


In [4]:
import numpy as np

# NumPy -> PyTorch
np_arr = np.array([10, 20, 30])
t_from_np = torch.from_numpy(np_arr)
print("NumPy 转成张量:", t_from_np)

# PyTorch -> NumPy
t = torch.tensor([40, 50, 60])
np_from_t = t.numpy()
print("张量转成 NumPy:", np_from_t)

NumPy 转成张量: tensor([10, 20, 30])
张量转成 NumPy: [40 50 60]


In [5]:
# 1. 创建两个矩阵 (2行3列) 和 (3行2列)
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.float32)

B = torch.tensor([[7, 8],
                  [9, 10],
                  [11, 12]], dtype=torch.float32)

# 2. 用 @ 符号做矩阵乘法
C = A @ B
print("PyTorch 结果:\n", C)
print("形状:", C.shape)  # 输出 (2, 2)

# 3. 转成 NumPy 验证一下（心里有底）
A_np = A.numpy()
B_np = B.numpy()
C_np = np.matmul(A_np, B_np)
print("NumPy 验证结果:\n", C_np)

# 4. 确认两者是否一致
if torch.allclose(C, torch.from_numpy(C_np)):
    print("✅ 计算完全正确！")
else:
    print("❌ 出错了")

PyTorch 结果:
 tensor([[ 58.,  64.],
        [139., 154.]])
形状: torch.Size([2, 2])
NumPy 验证结果:
 [[ 58.  64.]
 [139. 154.]]
✅ 计算完全正确！


In [6]:
import torch
import numpy as np

# 1. 创建一个 NumPy 数组
np_a = np.array([2.0, 3.0])

# 2. 创建一个 PyTorch 张量（开启“记仇”模式）
t_a = torch.tensor([2.0, 3.0], requires_grad=True)  # requires_grad=True 就是“开始记笔记”

# 3. 做同样的乘法运算
np_b = np_a * 2
t_b = t_a * 2

# 4. 假装我们算出了一个“损失值”（总和）
np_loss = np_b.sum()
t_loss = t_b.sum()

# 5. 关键时刻（区别出现了）：
#    NumPy：想反向传播？不好意思，我没有保留路径图。
#    PyTorch：没问题！执行反向传播。
t_loss.backward()  # 这一行在 NumPy 里会直接报错！

# 6. 查看张量的“原始数据”对于最终误差的贡献度（梯度）
print("张量 t_a 的梯度（对损失的敏感度）：", t_a.grad)  
# 输出: tensor([2., 2.]) 
# 解释：因为 t_a 乘以了 2，所以它对损失的敏感度就是 2。

张量 t_a 的梯度（对损失的敏感度）： tensor([2., 2.])


In [1]:
import torch
x = torch.tensor(3.0)       # 你的数据：一个普通的浮点数 3.0
x.requires_grad_(True)      # 给这个张量加装“追踪器”
y = x ** 2
print(y)  # 输出 tensor(9., grad_fn=<PowBackward0>)
y.backward()
print(x.grad)  # 输出: tensor(6.)

tensor(9., grad_fn=<PowBackward0>)
tensor(6.)
